apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: test-component-rfdt
  namespace: appstudio-e2e-test
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        appstudio.openshift.io/application: test-app-ifxq
        appstudio.openshift.io/component: test-component-rfdt
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: test-component-rfdt-
      labels:
        appstudio.openshift.io/application: test-app-ifxq
        appstudio.openshift.io/component: test-component-rfdt
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: appstudio-e2e-test
    spec:
      params:
      - name: git-url
        value: https://github.com/redhat-appstudio-qe/devfile-sample-python-basic
      - name: output-image
        value: quay.io/psturc/test-images:33af6c5dad1345d18c438266eaf271ea-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/hacbs-templates-bundle:13f5d9c921b3f727684a00084037f673a0dc4273
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: test-component-rfdt/$(tt.params.git-revision)
    status: {}
status: {}
